# Numpy 

In [3]:
import numpy as np

In [4]:
a=np.array([5,6,7,8,9,10,34,43,12,56,67,98,21,45])
print(a)

[ 5  6  7  8  9 10 34 43 12 56 67 98 21 45]


In [5]:
print(a.ndim)

1


In [6]:
a.shape

(14,)

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [9]:
b=np.array(["madhu","komal","rahul","piuu","renu","revti"])
print(b)

['madhu' 'komal' 'rahul' 'piuu' 'renu' 'revti']


In [10]:
type(b)

numpy.ndarray

In [11]:
b.shape

(6,)

In [12]:
b.ndim

1

In [13]:
b.reshape(3,2)

array([['madhu', 'komal'],
       ['rahul', 'piuu'],
       ['renu', 'revti']], dtype='<U5')

In [14]:
a.reshape(2,7)

array([[ 5,  6,  7,  8,  9, 10, 34],
       [43, 12, 56, 67, 98, 21, 45]])

In [15]:
a.sort()

In [16]:
print(a)

[ 5  6  7  8  9 10 12 21 34 43 45 56 67 98]


In [17]:
b.sort()

In [18]:
print(b)

['komal' 'madhu' 'piuu' 'rahul' 'renu' 'revti']


In [19]:
a1=np.array([34,89,46,99,100])
a2=np.array([45,32,45,78.98,89])

In [20]:
print(a1+a2)

[ 79.   121.    91.   177.98 189.  ]


# Two Dimentional Array

In [21]:
import numpy as np

In [22]:
f=np.array([[2,3,4,7],[23,56,78,34]])
print(f)

[[ 2  3  4  7]
 [23 56 78 34]]


In [23]:
f.shape

(2, 4)

In [24]:
f.reshape(4,2)

array([[ 2,  3],
       [ 4,  7],
       [23, 56],
       [78, 34]])

In [25]:
f.ndim

2

In [26]:
type(f)

numpy.ndarray

In [27]:
f.sort()

In [28]:
print(f)

[[ 2  3  4  7]
 [23 34 56 78]]


# For Loop

In [29]:
import numpy as np

In [30]:
d=np.array([[[34,76,56,45],[34,23,12,34],[43,23,12,23]]])
print(d)

[[[34 76 56 45]
  [34 23 12 34]
  [43 23 12 23]]]


In [31]:
d=np.array([[[34,76,56,45],[34,23,12,34],[43,23,12,23]]])
for x in d:
    print(x)

[[34 76 56 45]
 [34 23 12 34]
 [43 23 12 23]]


In [35]:
d=np.array([[[34,76,56,45],[34,23,12,34],[43,23,12,23]]])
for x in d:
    print("yes",x)
    for y in x:
        print("no",y)
    
        

yes [[34 76 56 45]
 [34 23 12 34]
 [43 23 12 23]]
no [34 76 56 45]
no [34 23 12 34]
no [43 23 12 23]


In [36]:
d=np.array([[[34,76,56,45],[34,23,12,34],[43,23,12,23]]])
for x in d:
    for y in x:
        for u in y:
            print("My name is madhu")

My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu
My name is madhu


In [37]:
k=np.array([[2,4,5,6,7,8,6,4,4,3,3,3],[3,4,5,6,7,8,9,3,2,1,3],[3,4,5,6,8,9,3,2,2,2]])
print(k)

[list([2, 4, 5, 6, 7, 8, 6, 4, 4, 3, 3, 3])
 list([3, 4, 5, 6, 7, 8, 9, 3, 2, 1, 3])
 list([3, 4, 5, 6, 8, 9, 3, 2, 2, 2])]


<ipython-input-37-06737b564538>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  k=np.array([[2,4,5,6,7,8,6,4,4,3,3,3],[3,4,5,6,7,8,9,3,2,1,3],[3,4,5,6,8,9,3,2,2,2]])


In [38]:
k.ndim

1

In [39]:
type(k)

numpy.ndarray

In [40]:
s1=np.array([2, 4, 5, 6, 7, 8, 6, 4, 4, 3, 3, 3])
s2=np.array([3, 4, 5, 6, 7, 8, 9, 3, 2, 1, 3])
s3=np.array([3, 4, 5, 6, 8, 9, 3, 2, 2, 2])

In [51]:
ab=np.concatenate((s1,s2,s3))      #concate the array
print(ab)

[2 4 5 6 7 8 6 4 4 3 3 3 3 4 5 6 7 8 9 3 2 1 3 3 4 5 6 8 9 3 2 2 2]


In [52]:
s4=np.array([2, 4, 5, 6, 7, 8, 6, 4, 4])
s5=np.array([3, 4, 5, 6, 7, 8, 9, 3, 2])
s6=np.array([3, 4, 5, 6, 8, 9, 3, 2, 2])

In [53]:
print(s4*s5*s6)

[ 18  64 125 216 392 576 162  24  16]


In [54]:
print(s4+s5+s6)

[ 8 12 15 18 22 25 18  9  8]


In [55]:
print(s4-s5+s6)

[2 4 5 6 8 9 0 3 4]


In [56]:
a=np.array([5,6,7,8,9,10,34,43,12,56,67,98,21,45])

In [57]:
np.where(a)       # give the position of element 

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       dtype=int64),)

In [58]:
np.sort(a)       # Asending Order 

array([ 5,  6,  7,  8,  9, 10, 12, 21, 34, 43, 45, 56, 67, 98])

In [59]:
np.flip(a)   # Reverse order of array

array([45, 21, 98, 67, 56, 12, 43, 34, 10,  9,  8,  7,  6,  5])

In [60]:
b=np.array_split(a,6)   # split the array
print(b)

[array([5, 6, 7]), array([ 8,  9, 10]), array([34, 43]), array([12, 56]), array([67, 98]), array([21, 45])]
